export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const COUNTRY_NAMES = 'COUNTRY_NAMES';
export const SUBMIT_BTN = 'SUBMIT_BTN';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const GET_COUNRTY_WEATHER = 'GET_COUNRTY_WEATHER';
